-- Credits schema and helper RPCs

create table if not exists public.user_credits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance int not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delta int not null,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.user_credits enable row level security;
alter table public.credit_ledger enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'user_credits' and policyname = 'own credits'
  ) then
    create policy "own credits" on public.user_credits for select using (auth.uid() = user_id);
  end if;
end $$;

do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'credit_ledger' and policyname = 'own ledger'
  ) then
    create policy "own ledger" on public.credit_ledger for select using (auth.uid() = user_id);
  end if;
end $$;

create or replace function public.grant_welcome_credits(p_user_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.user_credits (user_id, balance)
  values (p_user_id, 3)
  on conflict (user_id) do update set balance = greatest(public.user_credits.balance, 3), updated_at = now();

  insert into public.credit_ledger (user_id, delta, reason)
  values (p_user_id, 3, 'welcome')
  on conflict do nothing;
end;
$$;

revoke all on function public.grant_welcome_credits(uuid) from public;
grant execute on function public.grant_welcome_credits(uuid) to authenticated;

create or replace function public.adjust_credits(p_user_id uuid, p_delta int, p_reason text)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.credit_ledger (user_id, delta, reason) values (p_user_id, p_delta, p_reason);

  insert into public.user_credits (user_id, balance)
  values (p_user_id, greatest(p_delta, 0))
  on conflict (user_id) do update set balance = public.user_credits.balance + p_delta, updated_at = now();
end;
$$;

revoke all on function public.adjust_credits(uuid,int,text) from public;
grant execute on function public.adjust_credits(uuid,int,text) to authenticated;


